title: "Eco Atualidades"
description: "notícias do dia sobre sustentabilidade"
baseurl: "/ambipar-eco-atualidades"
url: "https://ambisocial.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
permalink: /:year/:month/:day/:title/
author:
  name: "Redação Eco Atualidades"
  email: "contato@ambipar-eco-atualidades.com"
social:
  name: Eco Atualidades
  links:
    - https://github.com/ambisocial/ambipar-eco-atualidades
