remote_theme: mmistakes/so-simple-theme
title: Eco Atualidades
description: Portal independente de notícias sobre sustentabilidade e economia circular
url: "https://ambisocial.github.io"
baseurl: "/eco-atualidades"
author: Redação Eco Atualidades
email: contato@eco-atualidades.com
lang: pt-BR
timezone: America/Sao_Paulo
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
markdown: kramdown
highlighter: rouge
paginate: 10
paginate_path: "/page:num/"
